[build]
  command = "npm run build"

[build.environment]
  NEXT_PUBLIC_API_URL = "/api/v1"

[[redirects]]
  from = "/api/v1/*"
  to = "https://am-i-a-good-match-api.onrender.com/api/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/backend-health"
  to = "https://am-i-a-good-match-api.onrender.com/health"
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"
